/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Submission = {
  _id: string;
  _type: "submission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  email: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  thesis: string;
  body: string;
  sources: Array<string>;
  submittedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type PullQuote = {
  _type: "pullQuote";
  text: string;
  attribution?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  dek?: string;
  slug: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  postType: "dispatch" | "editorial";
  publishedAt?: string;
  issueLabel?: string;
  body?: BlockContent;
  sources?: Array<{
    label: string;
    citation: string;
    _type: "sourceItem";
    _key: string;
  }>;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & ActionBox)
  | ({
      _key: string;
    } & FactBox)
  | ({
      _key: string;
    } & PullQuote)
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type FactBox = {
  _type: "factBox";
  title?: string;
  items?: Array<{
    label?: string;
    text: string;
    _type: "factBoxItem";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ActionBox = {
  _type: "actionBox";
  title?: string;
  items?: Array<{
    label?: string;
    text: string;
    _type: "actionBoxItem";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Submission
  | SanityImageCrop
  | SanityImageHotspot
  | PullQuote
  | AuthorReference
  | CategoryReference
  | Post
  | BlockContent
  | Slug
  | FactBox
  | Category
  | Author
  | ActionBox
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: ALL_POST_SLUGS
// Query: *[_type == "post" && defined(slug.current)]{  "slug": slug.current,  _updatedAt}
export type ALL_POST_SLUGS_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: FIRST_POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  title,  dek,  postType,  body,  "excerpt": pt::text(body),  mainImage,  publishedAt,  issueLabel,  sources,  _updatedAt,  "categories": coalesce(    categories[]->{      _id,      slug,      title    },    []  ),  "author": coalesce(    author->{      name,      image    },    *[_id == "author-the-dispatch"][0]{      name,      image    }  )}
export type FIRST_POST_QUERY_RESULT = {
  _id: string;
  title: string;
  dek: string | null;
  postType: "dispatch" | "editorial";
  body: BlockContent | null;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  issueLabel: string | null;
  sources: Array<{
    label: string;
    citation: string;
    _type: "sourceItem";
    _key: string;
  }> | null;
  _updatedAt: string;
  categories:
    | Array<{
        _id: string;
        slug: Slug;
        title: string;
      }>
    | Array<never>;
  author:
    | {
        name: null;
        image: null;
      }
    | {
        name: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PAGINATED_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0...12]{  _id,  title,  dek,  postType,  slug,  publishedAt,  issueLabel,  "categories": coalesce(    categories[]->{      _id,      slug,      title    },    []  )}
export type PAGINATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  dek: string | null;
  postType: "dispatch" | "editorial";
  slug: Slug;
  publishedAt: string | null;
  issueLabel: string | null;
  categories:
    | Array<{
        _id: string;
        slug: Slug;
        title: string;
      }>
    | Array<never>;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "post" && defined(slug.current)]{\n  "slug": slug.current,\n  _updatedAt\n}': ALL_POST_SLUGS_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id,\n  title,\n  dek,\n  postType,\n  body,\n  "excerpt": pt::text(body),\n  mainImage,\n  publishedAt,\n  issueLabel,\n  sources,\n  _updatedAt,\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      slug,\n      title\n    },\n    []\n  ),\n  "author": coalesce(\n    author->{\n      name,\n      image\n    },\n    *[_id == "author-the-dispatch"][0]{\n      name,\n      image\n    }\n  )\n}': FIRST_POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]|order(publishedAt desc)[0...12]{\n  _id,\n  title,\n  dek,\n  postType,\n  slug,\n  publishedAt,\n  issueLabel,\n  "categories": coalesce(\n    categories[]->{\n      _id,\n      slug,\n      title\n    },\n    []\n  )\n}': PAGINATED_POSTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
